<a href="https://colab.research.google.com/github/pdalikkcf/Test/blob/main/Visualize_YT_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

YT Data Visualization Codedex Activity

In [12]:
from google.colab import files

uploaded = files.upload()

Saving most_subscribed_youtube_channels.csv to most_subscribed_youtube_channels.csv

In [13]:
import pandas as pd
import io

In [14]:
import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels.csv']))
display(df)

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,T-Series,"222,000,000","198,459,090,822","17,317",Music,2006
1,2,YouTube Movies,"154,000,000",0,0,Film & Animation,2015
2,3,Cocomelon - Nursery Rhymes,"140,000,000","135,481,339,848",786,Education,2006
3,4,SET India,"139,000,000","125,764,252,686","91,271",Shows,2006
4,5,Music,"116,000,000",0,0,NaN,2013
...,...,...,...,...,...,...,...
995,996,JP Plays,"10,900,000","4,609,300,218","3,528",Gaming,2014
996,997,TrapMusicHDTV,"10,900,000","4,070,521,973",690,Music,2013
997,998,Games EduUu,"10,900,000","3,093,784,767","1,006",Gaming,2011
998,999,Hueva,"10,900,000","3,040,301,750",831,Gaming,2012
999,1000,Dobre Brothers,"10,900,000","2,808,411,693",590,People & Blogs,2017

In [15]:
#df = df.replace(',', ' ', regex=True)
df['subscribers'] = df['subscribers'].str.replace(',', '').astype(float)
df['video views'] = df['video views'].str.replace(',', '').astype(float)
df['video count'] = df['video count'].str.replace(',', '').astype(float)
display(df)

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,T-Series,222000000.0,1.984591e+11,17317.0,Music,2006
1,2,YouTube Movies,154000000.0,0.000000e+00,0.0,Film & Animation,2015
2,3,Cocomelon - Nursery Rhymes,140000000.0,1.354813e+11,786.0,Education,2006
3,4,SET India,139000000.0,1.257643e+11,91271.0,Shows,2006
4,5,Music,116000000.0,0.000000e+00,0.0,NaN,2013
...,...,...,...,...,...,...,...
995,996,JP Plays,10900000.0,4.609300e+09,3528.0,Gaming,2014
996,997,TrapMusicHDTV,10900000.0,4.070522e+09,690.0,Music,2013
997,998,Games EduUu,10900000.0,3.093785e+09,1006.0,Gaming,2011
998,999,Hueva,10900000.0,3.040302e+09,831.0,Gaming,2012
999,1000,Dobre Brothers,10900000.0,2.808412e+09,590.0,People & Blogs,2017

**Section 1: Make a Histogram**

In [16]:
import plotly.express as px

In [17]:
fig = px.histogram(df, x='subscribers', title='Subscriber Count')
fig.show()

**Section 2: Make a Pie Chart**

In [18]:
import plotly.express as px

fig = px.pie(df, values='subscribers', names='category', title='YouTube Categories')
fig.show()

**Section 3: Make a Box Plot**

In [19]:
import plotly.express as px

fig = px.box(df, y='started', title='Years Started')
fig.show()